---
- name: (Alpine Linux) Install logrotate
  community.general.apk:
    name: logrotate
  when: ansible_facts['os_family'] == 'Alpine'

- name: (Debian/Ubuntu) Install logrotate
  ansible.builtin.apt:
    name: logrotate
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: (Amazon Linux/CentOS/Oracle Linux/RHEL) Install logrotate
  ansible.builtin.yum:
    name: logrotate
    state: present
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - "{{ ansible_facts['distribution'] }} {{ ansible_facts['system'] }} {{ ansible_facts['distribution_version'] }}" != 'Amazon Linux 2023'

- name: (Amazon Linux 2023) Install logrotate
  ansible.builtin.dnf:
    name: logrotate
    state: present
  when:
    - "{{ ansible_facts['distribution'] }} {{ ansible_facts['system'] }} {{ ansible_facts['distribution_version'] }}" == 'Amazon Linux 2023'

- name: (SLES) Install Logrotate
  community.general.zypper:
    name: logrotate
    state: present
  when: ansible_facts['os_family'] == 'Suse'

- name: Create logrotate config
  ansible.builtin.template:
    src: logrotate/nginx.j2
    dest: /etc/logrotate.d/nginx
    mode: "0644"
  notify: (Handler) Run logrotate
